version: "3.3"

services:
  orders_tracking_db:
    container_name: orders_tracking_db
    hostname: orders_tracking_db
    image: postgres:13.3
    restart: always
    user: root
    networks:
      - kafka-net
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=orders_tracking
    volumes:
      - ./postgres-data:/var/lib/postgresql
    ports:
      - "5432:5432"

  orders_tracking_db_migrations:
    container_name: orders_tracking_db_migrations
    build: ./
    command: /bin/sh -c "/usr/local/bin/goose postgres up -dir ./migrations"
    networks:
      - kafka-net
    depends_on:
      - orders_tracking_db

  orders_tracking:
    container_name: orders_tracking
    build: ./
    command: /bin/sh -c "/usr/local/bin/orders_tracking"
    networks:
      - kafka-net
    depends_on:
      - redis
      - orders_tracking_db
      - orders_tracking_db_migrations

  redis:
    image: 'bitnami/redis:latest'
    restart: always
    ports:
      - '6379:6379'
    environment:
      - REDIS_PASSWORD=redis_pass
    networks:
      - kafka-net

networks:
  kafka-net:
    driver: bridge