
application:
  name: "orders_tracking"
  testData: true

database:
  dbms: "postgres"
  db: "orders_tracking"
  host: orders_tracking_db
#  host: localhost
  port: 5432
  user: "postgres"
  password: "postgres"

kafka:
  brokers:
    - host: "localhost"
      port: 9095
    - host: "localhost"
      port: 9097
    - host: "localhost"
      port: 9097

  issueOrderTopics:
    issueOrder: "IssueOrder"
    removeOrder: "RemoveOrder"
    markOrderIssued: "MarkOrderIssued"
    undoIssueOrder: "UndoIssueOrder"
    confirmIssueOrder: "ConfirmIssueOrder"
