
application:
  name: "orders_tracking"
  testData: true

database:
  dbms: "postgres"
  db: "orders_tracking"
#  host: orders_tracking_db
#  host: localhost
  host: 172.17.0.1
  port: 5432
  user: "postgres"
  password: "postgres"

kafka:
  brokers:
    - host: "172.17.0.1"
      port: 19092
    - host: "172.17.0.1"
      port: 29092
    - host: "172.17.0.1"
      port: 39092

  issueOrderTopics:
    issueOrder: "IssueOrder"
    removeOrder: "RemoveOrder"
    markOrderIssued: "MarkOrderIssued"
    undoIssueOrder: "UndoIssueOrder"
    confirmIssueOrder: "ConfirmIssueOrder"
